### ISSUE TITLE
"Back to Top" link on the main site.

### ISSUE THREAD

**Issue by TotoB12** [free-for-life/free-for-life#17]
On this repository's README, the link is correct and functions correctly, but on the live web site, the link also return to [https://free-for.life/#/?id=-table-of-contents](https://free-for.life/#/?id=-table-of-contents), although it should be [https://free-for.life/#/?id=%f0%9f%93%9c-table-of-contents](https://free-for.life/#/?id=%f0%9f%93%9c-table-of-contents).

**Comment by Jeymen** [comment]
I want to work on this.

**Comment by Jeymen** [comment]
@WilliamDavidHarrison I wanna work on this.

**Comment by Jeymen** [comment]
I don't see any issue, could you please provide more information and screenshot(s) of the issue??

**Comment by Jeymen** [comment]
@TotoB12 I don't see any issue, could you please provide more information and screenshot(s) of the issue??

**Comment by WilliamDavidHarrison** [comment]
Sorry, I forgot to reply to this issue, this issue was resolved in a73725c9efcf726f8d922ac82b3a244b32267a8c.

**Comment by TotoB12** [comment]
Cool, thanks.
And great job on the site!
