### ISSUE TITLE
Free Stable diffusion API

### ISSUE THREAD

**Issue by Metim0l** [free-for-life/free-for-life#31]
Hello! I've created my own completely free image generation api. Thought you might be interested in adding it to your list. There are many different models of stable dufusion available. Here is the link to documentation: https://github.com/Metim0l/VisionCraft

**Comment by Jeymen** [comment]
Hi, thank you for your interest in contributing. This will be reviewed and possibly considered. Thank you for the contribution.

**Comment by WilliamDavidHarrison** [comment]
Unfortunately I will not be able to add this to the list as we do not support self-hosted services.
