### ISSUE TITLE
Table of Contents Outdated

### ISSUE THREAD

**Issue by fiftys7ven** [free-for-life/free-for-life#35]
Edit: In SSL Category, when i press SSL.com site it redericts to letsencrypt.org - it should rederict to https://SSL.com

Theres no new category (SSL) in readme and on websites "Table of Contents".

**Comment by Jeymen** [comment]
I will look into it as soon as I can. Thank you for informing us.

**Comment by WilliamDavidHarrison** [comment]
I have fixed both issues, thank you for the report 👍
