### ISSUE TITLE
DanBot Hosting

### ISSUE THREAD

**Issue by andrewstech** [free-for-life/free-for-life#40]
You work for them and forgot to add to list bruh

**Comment by WilliamDavidHarrison** [comment]
*Technically*, it falls under [our disallowed services](https://free-for.life/#/contributing?id=%f0%9f%9a%ab-disallowed-services), specifically `Self hosted services`.

It is a registered company however, so I will consider adding it to the list.

**Comment by andrewstech** [comment]
Lol do it you can add hosting by is-a.dev while your at it

**Comment by WilliamDavidHarrison** [comment]
I've decided I won't add DanBot Hosting since it is technically a self-hosted service however I will add in the description of is-a.dev that they support hosting.
